services:
  # Frontend service
  frontend:
    container_name: frontend-1
    image: victor750/budget-app-frontend:2.2.2
    ports:
      - 3000:3000
    networks:
      - shared-network
  # Backend service
  backend:
    container_name: backend-1
    image: victor750/budget-app-backend:2.2.2
    ports:
      - 4000:4000
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PASS=mypass
    networks:
      - shared-network
  # Database service
  postgres:
    container_name: postgres-1
    image: postgres:14.6
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=mypass
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - shared-network
volumes:
  pgdata:
networks:
  shared-network:
