apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back-app
  template:
    metadata:
      labels:
        app: back-app
    spec:
      containers:
        - name: back-app
          image: victor750/budget-app-backend:2.2.2
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secrets-ag
                  key: DB_PASSWORD
            - name: DB_HOST
              value: pg-service
          resources:
            limits:
              memory: "256Mi"
              cpu: "256m"
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: back-service
spec:
  type: LoadBalancer
  selector:
    app: back-app
  ports:
    - port: 4000
      targetPort: 4000
